#! /bin/bash
 
# originaly from http://tinyurl.com/twitch-linux from taladan
# www.youtube.com/user/taladan
 
# gist created by brodul
 
INRES="1280x800" # input resolution
#OUTRES="1024x640" # Output resolution
OUTRES="800x500" # Output resolution
FPS="30" # target FPS
QUAL="normal" # one of the many FFMPEG preset on (k)ubuntu found in /usr/share/ffmpeg
# If you have low bandwidth, put the qual preset on 'fast' (upload bandwidth)
# If you have medium bandwitch put it on normal to medium
 
# Write your key in a file named .twitch_key in your home directory
STREAM_KEY=$(cat ~/.twitch_key) # This is your streamkey generated by jtv/twitch found at: http://www.justin.tv/broadcast/adv_other
 
avconv \
-f video4linux2 -s $INRES -r "$FPS" -i /dev/video0 \
-f alsa -ac 1 -i hw:0,0 \
-vcodec libx264 -s $OUTRES \
-acodec libmp3lame -ar 44100 -threads 1 -qscale 3 -b 712000 -bufsize 512k \
-f flv "rtmp://live.justin.tv/app/$STREAM_KEY"
